<a href="https://colab.research.google.com/github/AoShuang92/PhD_tutorial/blob/main/percentile_for_boundaries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [11]:
bb = np.array([-0.5, 0.2, 1.5, 2])
normed = bb / max(bb)
normed

gemma = -0.2 
opt_t = 2
norm_ece_level = normed

result = opt_t * (1+ norm_ece_level * gemma)
print(result)

[2.1  1.96 1.7  1.6 ]


In [27]:
bb = np.array([-0.5, -0.2,-0.1, 0.1, 0.5])
normed = bb / max(bb)
normed

gemma = 0.02 
opt_t = 0.8
norm_ece_level = normed

result = opt_t * (1+ norm_ece_level * gemma)
print(result, -1.5/result)
import torch.nn.functional as F
import torch
tt = torch.tensor(-1.5/result)
F.softmax(tt.unsqueeze(0), dim=1)

[0.784  0.7936 0.7968 0.8032 0.816 ] [-1.91326531 -1.89012097 -1.88253012 -1.86752988 -1.83823529]


tensor([[0.1931, 0.1976, 0.1991, 0.2021, 0.2081]], dtype=torch.float64)

In [22]:
bb = np.array([-0.5, -0.2,-0.1, 0.1, 0.5])
normed = bb / max(bb)
normed

gemma = -0.02 
opt_t = 0.8
norm_ece_level = normed

result = opt_t * (1+ norm_ece_level * gemma)
print(result, -1.5/result)

[0.816  0.8064 0.8032 0.7968 0.784 ] [-1.83823529 -1.86011905 -1.86752988 -1.88253012 -1.91326531]


In [26]:
import torch.nn.functional as F
import torch
tt = torch.tensor(-1.5/result)
F.softmax(tt.unsqueeze(0), dim=1)

tensor([[0.2069, 0.2024, 0.2009, 0.1979, 0.1919]], dtype=torch.float64)

In [13]:
bb = np.array([-0.5, 0.2, 1.5, 2])
normed = bb / max(bb)
print(normed)

gemma = 0.2 
opt_t = 2
norm_ece_level = normed

result = opt_t * (1+ norm_ece_level * gemma)
print(result)

[-0.25  0.1   0.75  1.  ]
[1.9  2.04 2.3  2.4 ]


In [14]:
cc = bb [bb>=3]
cc

array([], dtype=float64)

In [14]:
cc.mean()

<ipython-input-14-efc7b2d3f397>:1: RuntimeWarning: Mean of empty slice.
  cc.mean()
/usr/local/lib/python3.8/dist-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


nan

In [37]:
import numpy as np
bb = np.array([-7, -5, -1, 0.2, 1.5, 2, 7, 9])
q1 = np.percentile(bb, 25, interpolation = 'midpoint')
q3 = np.percentile(bb, 75, interpolation = 'midpoint')
IQR = q3 - q1
upper = q3 + 1.5 * IQR
lower = q1 - 1.5 * IQR
q1, q3, lower, upper

(-3.0, 4.5, -14.25, 15.75)

In [38]:
# bb = np.array([-15, -1, 0.2, 1.5, 2, 20])
bb[bb<lower] = lower
bb

array([-7. , -5. , -1. ,  0.2,  1.5,  2. ,  7. ,  9. ])

In [39]:
bb[bb>upper] = upper
bb

array([-7. , -5. , -1. ,  0.2,  1.5,  2. ,  7. ,  9. ])